name: Deploy pages

on:
  push:
    branches:
      - main # Update to 'master' if your default branch is named master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      # 👇 1. Setup pnpm before setting up Node
      - uses: pnpm/action-setup@v4
        with:
          version: 10 # You can lock to a specific version here
      
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm' # 👈 2. Cache pnpm instead of yarn
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile # 👈 3. Switched to pnpm
        
      #- name: Install Playwright
      #  run: npx playwright install chromium
        
      - name: Build
        run: pnpm build --base "./" # 👈 4. Switched to pnpm
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5