name: Deploy pages

on:
  push:
    branches:
      - main # Update to 'master' if your default branch is named master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Use latest checkout version to avoid Node 20 deprecation warnings
      - uses: actions/checkout@v5
      
      # Use latest setup-node version to avoid Node 20 deprecation warnings
      - uses: actions/setup-node@v6
        with:
          node-version: '24' # 👈 Switched to 24 here
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      #- name: Install Playwright
      #  run: npx playwright install chromium
        
      - name: Build
        run: yarn build --base "./"
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5